// Alice on Azure (Tuduma tenant, UK South). Built in three stages by deploy/azure-setup.ps1:
//   stage 'infra'   network, PostgreSQL (private), Key Vault, registry, file share, Container Apps environment, identity
//   stage 'migrate' + the two migration jobs (dry run and apply), run once at cut-over, inside the network
//   stage 'apps'    + alice-web (chat and Command centre, Entra sign-in, Stefan only) and alice-mcp (external MCP endpoint)
//   backup = true   + backup.bicep (with stage apps): file share snapshots, the resource group lock, the nightly off-site copy
// No secret values live here or in git: API keys are put into Key Vault by the script; the apps read them by managed identity.
targetScope = 'resourceGroup'

@description('Azure region.')
param location string = 'uksouth'
@description('Short name used in resource names.')
param prefix string = 'alice'
@allowed(['infra', 'migrate', 'apps'])
param stage string = 'infra'
@description('Container image, e.g. <registry>.azurecr.io/alice:<tag>. Needed from stage migrate on.')
param image string = ''
@description('PostgreSQL administrator login.')
param pgAdminLogin string = 'aliceadmin'
@secure()
@description('PostgreSQL administrator password (letters and digits; generated by the script).')
param pgAdminPassword string
@description('Object ID of the person running the deployment (to put secrets into Key Vault).')
param deployerObjectId string
@description('Your name, recorded as the actor when no sign-in name is present.')
param ownerName string = 'Stefan'
@description('Your Entra object ID: the only person the web sign-in lets in.')
param ownerObjectId string = ''
@description('Other Entra object IDs allowed to sign in (e.g. your everyday account in the same tenant). The owner is always allowed.')
param allowedUserObjectIds array = []
@description('Ask for your sign-in (not just reuse the browser\'s Microsoft session) at every new Alice session.')
param askEverySignIn bool = true
@description('Custom domain for alice-web (e.g. alice.northants.it), already bound once with a managed certificate; empty = none.')
param customDomain string = ''
@description('Resource ID of that domain\'s managed certificate.')
param customDomainCertificateId string = ''
@description('Client ID of the "Alice web sign-in" app registration (created by the script before stage apps).')
param webAuthClientId string = ''
@description('Environment variable name -> Key Vault secret name, for the API keys you have stored.')
param keyVaultSecretNames object = {}
@description('External endpoint: Alice API app registration client ID.')
param extAppId string = ''
@description('External endpoint: allowed user object IDs, comma separated.')
param extAllowedUsers string = ''
@description('External endpoint: allowed client apps, <client app id>=<label>:<provider>;...')
param extCallers string = ''
@description('More token audiences: the Application ID URIs from Microsoft 365 Copilot\'s Entra SSO registrations (comma separated).')
param extAudiences string = ''
@description('Mailbox Alice sends from (notify.py, through Microsoft Graph with the managed identity): set by azure-setup -Step mail.')
param mailFrom string = ''
@description('Alice\'s public address, for links in emails (e.g. https://alice.northants.it).')
param publicUrl string = ''
@description('Claude connector: client ID of the "Alice connector sign-in" app registration (its secret and signing key are in Key Vault); empty = off.')
param connectorClientId string = ''

// ---------------- backups (azure-setup.ps1 -Step backup; every later step keeps these) ----------------
@description('Backups on: Azure Backup for the file share, the resource group lock and the nightly off-site copy (infra/backup.bicep).')
param backup bool = false
@minValue(7)
@maxValue(35)
@description('Days of PostgreSQL backups kept (point-in-time restore to any moment in them). 35 is the most Azure allows.')
param pgBackupRetentionDays int = 35
@description('Geo-redundant database backups (a copy in UK West). Azure only allows choosing this when the server is created: see the PR and docs.')
param pgGeoRedundantBackup bool = false
@description('Days of daily file share snapshots kept in the Recovery Services vault.')
param filesBackupDays int = 30
@description('Days each nightly off-site copy is kept unchangeable (immutability), then removed.')
param offsiteKeepDays int = 35
@description('Days a deleted off-site copy stays recoverable (soft delete).')
param offsiteSoftDeleteDays int = 35
@description('Region of the separate off-site storage account.')
param offsiteLocation string = 'ukwest'
@description('True once the off-site immutability policy is locked (it is then never redeployed).')
param offsiteImmutabilityLocked bool = false
@description('A CanNotDelete lock on the whole resource group (on by default with backups).')
param lockResourceGroup bool = true
@description('Who is emailed when a nightly backup fails (needs -Step mail for sending).')
param backupNotify string = ''

var suffix = take(uniqueString(resourceGroup().id), 6)
var acrName = '${prefix}${suffix}acr'
var kvName = '${prefix}-kv-${suffix}'
var storageName = '${prefix}${suffix}files'
var withJobs = stage == 'migrate' || stage == 'apps'
var withApps = stage == 'apps'
var withBackup = backup && withApps
var backupVaultName = '${prefix}-backup-vault'
var offsiteName = '${prefix}${suffix}offsite'

// ---------------- monitoring ----------------
resource logs 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {
  name: '${prefix}-logs'
  location: location
  properties: { sku: { name: 'PerGB2018' }, retentionInDays: 90 }
}

// ---------------- network: apps and database share a private network ----------------
resource vnet 'Microsoft.Network/virtualNetworks@2023-09-01' = {
  name: '${prefix}-vnet'
  location: location
  properties: {
    addressSpace: { addressPrefixes: ['10.40.0.0/16'] }
    subnets: [
      {
        name: 'apps'
        properties: {
          addressPrefix: '10.40.0.0/23'
          delegations: [{ name: 'aca', properties: { serviceName: 'Microsoft.App/environments' } }]
        }
      }
      {
        name: 'database'
        properties: {
          addressPrefix: '10.40.2.0/24'
          delegations: [{ name: 'pg', properties: { serviceName: 'Microsoft.DBforPostgreSQL/flexibleServers' } }]
        }
      }
    ]
  }
}

resource pgDns 'Microsoft.Network/privateDnsZones@2020-06-01' = {
  name: '${prefix}.private.postgres.database.azure.com'
  location: 'global'
}

resource pgDnsLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2020-06-01' = {
  parent: pgDns
  name: '${prefix}-vnet-link'
  location: 'global'
  properties: { registrationEnabled: false, virtualNetwork: { id: vnet.id } }
}

// ---------------- PostgreSQL (private access only, daily backups with point-in-time restore) ----------------
resource pg 'Microsoft.DBforPostgreSQL/flexibleServers@2022-12-01' = {
  name: '${prefix}-pg-${suffix}'
  location: location
  sku: { name: 'Standard_B1ms', tier: 'Burstable' }
  properties: {
    version: '16'
    administratorLogin: pgAdminLogin
    administratorLoginPassword: pgAdminPassword
    storage: { storageSizeGB: 32 }
    backup: { backupRetentionDays: pgBackupRetentionDays, geoRedundantBackup: pgGeoRedundantBackup ? 'Enabled' : 'Disabled' }
    network: { delegatedSubnetResourceId: vnet.properties.subnets[1].id, privateDnsZoneArmResourceId: pgDns.id }
    highAvailability: { mode: 'Disabled' }
  }
  dependsOn: [pgDnsLink]
}

resource pgExtensions 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2022-12-01' = {
  parent: pg
  name: 'azure.extensions'
  properties: { value: 'CITEXT', source: 'user-override' }
}

resource pgDatabase 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2022-12-01' = {
  parent: pg
  name: 'alice'
  properties: { charset: 'UTF8', collation: 'en_US.utf8' }
  dependsOn: [pgExtensions]
}

// ---------------- identity, registry, Key Vault ----------------
resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: '${prefix}-identity'
  location: location
}

resource acr 'Microsoft.ContainerRegistry/registries@2023-07-01' = {
  name: acrName
  location: location
  sku: { name: 'Basic' }
  properties: { adminUserEnabled: false }
}

resource kv 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: kvName
  location: location
  properties: {
    tenantId: tenant().tenantId
    sku: { family: 'A', name: 'standard' }
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 30
    enablePurgeProtection: true
  }
}

resource dbUrlSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: kv
  name: 'database-url'
  properties: {
    value: 'host=${pg.properties.fullyQualifiedDomainName} port=5432 dbname=alice user=${pgAdminLogin} password=${pgAdminPassword} sslmode=require'
  }
}

var roles = {
  acrPull: '7f951dda-4ed3-4680-a7ca-43fe172d538d'
  kvSecretsUser: '4633458b-17de-408a-b874-0445c86b69e6'
  kvSecretsOfficer: 'b86a8fe4-44ce-4948-aee5-eccb2c155cd7'
}

resource identityAcrPull 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(acr.id, identity.id, roles.acrPull)
  scope: acr
  properties: { roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.acrPull), principalId: identity.properties.principalId, principalType: 'ServicePrincipal' }
}

resource identityKvRead 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(kv.id, identity.id, roles.kvSecretsUser)
  scope: kv
  properties: { roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.kvSecretsUser), principalId: identity.properties.principalId, principalType: 'ServicePrincipal' }
}

resource deployerKvWrite 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(kv.id, deployerObjectId, roles.kvSecretsOfficer)
  scope: kv
  properties: { roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.kvSecretsOfficer), principalId: deployerObjectId, principalType: 'User' }
}

// ---------------- file share: Documents (templates, policy library, references) and data (images, imports) ----------------
resource storage 'Microsoft.Storage/storageAccounts@2023-01-01' = {
  name: storageName
  location: location
  sku: { name: 'Standard_LRS' }
  kind: 'StorageV2'
  properties: { minimumTlsVersion: 'TLS1_2', allowBlobPublicAccess: false, supportsHttpsTrafficOnly: true }
}

resource files 'Microsoft.Storage/storageAccounts/fileServices@2023-01-01' = {
  parent: storage
  name: 'default'
  properties: { shareDeleteRetentionPolicy: { enabled: true, days: 14 } }
}

resource share 'Microsoft.Storage/storageAccounts/fileServices/shares@2023-01-01' = {
  parent: files
  name: 'alice'
  properties: { shareQuota: 100 }
}

// ---------------- Container Apps environment ----------------
resource env 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: '${prefix}-env'
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: { customerId: logs.properties.customerId, sharedKey: logs.listKeys().primarySharedKey }
    }
    vnetConfiguration: { infrastructureSubnetId: vnet.properties.subnets[0].id, internal: false }
    workloadProfiles: [{ name: 'Consumption', workloadProfileType: 'Consumption' }]
  }
}

resource envFiles 'Microsoft.App/managedEnvironments/storages@2024-03-01' = {
  parent: env
  name: 'alice-files'
  properties: {
    azureFile: { accountName: storage.name, accountKey: storage.listKeys().keys[0].value, shareName: share.name, accessMode: 'ReadWrite' }
  }
}

// ---------------- what every Alice container gets ----------------
var webName = '${prefix}-web'
var mcpName = '${prefix}-mcp'
var webFqdn = '${webName}.${env.properties.defaultDomain}'
var mcpFqdn = '${mcpName}.${env.properties.defaultDomain}'
var kvUri = kv.properties.vaultUri
var keySecretNames = [for k in items(keyVaultSecretNames): { name: toLower(replace(k.key, '_', '-')), env: k.key, kv: k.value }]
var secrets = concat(
  [{ name: 'database-url', keyVaultUrl: '${kvUri}secrets/database-url', identity: identity.id }],
  map(keySecretNames, s => { name: s.name, keyVaultUrl: '${kvUri}secrets/${s.kv}', identity: identity.id })
)
var connectorSecrets = empty(connectorClientId) ? [] : [
  { name: 'connector-secret', keyVaultUrl: '${kvUri}secrets/connector-secret', identity: identity.id }
  { name: 'connector-key', keyVaultUrl: '${kvUri}secrets/connector-key', identity: identity.id }
]
var connectorEnv = empty(connectorClientId) ? [] : [
  { name: 'ALICE_EXT_CONNECTOR_CLIENT_ID', value: connectorClientId }
  { name: 'ALICE_EXT_CONNECTOR_SECRET', secretRef: 'connector-secret' }
  { name: 'ALICE_EXT_CONNECTOR_KEY', secretRef: 'connector-key' }
]
// What backup.py needs to know (the Backup page, and the alice-backup job). Empty until -Step backup.
var backupEnv = !backup ? [] : [
  { name: 'ALICE_BACKUP_ACCOUNT', value: offsiteName }
  { name: 'ALICE_BACKUP_CONTAINER', value: 'alice-offsite' }
  { name: 'ALICE_BACKUP_REGION', value: offsiteLocation == 'ukwest' ? 'UK West' : offsiteLocation }
  { name: 'ALICE_BACKUP_KEEP_DAYS', value: string(offsiteKeepDays) }
  { name: 'ALICE_BACKUP_SOFT_DELETE_DAYS', value: string(offsiteSoftDeleteDays) }
  { name: 'ALICE_BACKUP_IMMUTABILITY_LOCKED', value: offsiteImmutabilityLocked ? '1' : '0' }
  { name: 'ALICE_BACKUP_NOTIFY', value: backupNotify }
  { name: 'ALICE_FILES_ACCOUNT', value: storageName }
  { name: 'ALICE_BACKUP_VAULT_ID', value: resourceId('Microsoft.RecoveryServices/vaults', backupVaultName) }
  { name: 'ALICE_BACKUP_FILES_DAYS', value: string(filesBackupDays) }
  { name: 'ALICE_BACKUP_FILES_TIME', value: '01:00' }
  { name: 'ALICE_PG_SERVER_ID', value: pg.id }
  { name: 'ALICE_PG_BACKUP_DAYS', value: string(pgBackupRetentionDays) }
  { name: 'ALICE_PG_GEO_BACKUP', value: pgGeoRedundantBackup ? '1' : '0' }
  { name: 'ALICE_BACKUP_LOCK', value: lockResourceGroup ? 'alice-do-not-delete' : '' }
]
var commonEnv = concat(
  [
    { name: 'ALICE_DATABASE_URL', secretRef: 'database-url' }
    { name: 'AISUBSTRATE_DATA_DIR', value: '/mnt/alice/data' }
    { name: 'ALICE_DOCUMENT_LIBRARY', value: '/mnt/alice/Documents' }
    { name: 'ALICE_OWNER_NAME', value: ownerName }
    { name: 'ALICE_AUDIT_STDOUT', value: '1' }
    // keyvault.py: optional keys added in the portal are read at run time (allow-listed names only)
    { name: 'ALICE_KEY_VAULT_URI', value: kvUri }
    { name: 'ALICE_IDENTITY_CLIENT_ID', value: identity.properties.clientId }
    // notify.py: held decisions emailed to their owner (only once -Step mail has set the mailbox)
    { name: 'ALICE_MAIL_FROM', value: mailFrom }
    { name: 'ALICE_PUBLIC_URL', value: publicUrl }
    // backup.py: the Backup page is for the owner only (their Entra object ID), and shows these backups
    { name: 'ALICE_OWNER_OBJECT_ID', value: ownerObjectId }
  ],
  backupEnv,
  map(keySecretNames, s => { name: s.env, secretRef: s.name })
)
var volumes = [{ name: 'alice', storageType: 'AzureFile', storageName: envFiles.name, mountOptions: 'uid=10001,gid=10001,dir_mode=0770,file_mode=0660' }]
var mounts = [{ volumeName: 'alice', mountPath: '/mnt/alice' }]
var registries = [{ server: acr.properties.loginServer, identity: identity.id }]
var tcpProbes = [
  { type: 'Startup', tcpSocket: { port: 0 }, initialDelaySeconds: 5, periodSeconds: 5, failureThreshold: 24 }
]

// ---------------- migration jobs (stage migrate): copy the PC's SQLite database into PostgreSQL ----------------
resource migrateCheck 'Microsoft.App/jobs@2024-03-01' = if (withJobs) {
  name: '${prefix}-migrate-check'
  location: location
  identity: { type: 'UserAssigned', userAssignedIdentities: { '${identity.id}': {} } }
  properties: {
    environmentId: env.id
    workloadProfileName: 'Consumption'
    configuration: { triggerType: 'Manual', replicaTimeout: 1800, replicaRetryLimit: 0, manualTriggerConfig: { parallelism: 1, replicaCompletionCount: 1 }, registries: registries, secrets: secrets }
    template: {
      containers: [{ name: 'migrate', image: image, resources: { cpu: json('0.5'), memory: '1Gi' }, env: concat(commonEnv, [{ name: 'ALICE_ROLE', value: 'migrate' }, { name: 'MIGRATE_APPLY', value: '0' }, { name: 'MIGRATE_SOURCE', value: '/mnt/alice/migrate/substrate.db' }]), volumeMounts: mounts }]
      volumes: volumes
    }
  }
  dependsOn: [identityAcrPull, identityKvRead, dbUrlSecret, pgDatabase]
}

resource migrateApply 'Microsoft.App/jobs@2024-03-01' = if (withJobs) {
  name: '${prefix}-migrate-apply'
  location: location
  identity: { type: 'UserAssigned', userAssignedIdentities: { '${identity.id}': {} } }
  properties: {
    environmentId: env.id
    workloadProfileName: 'Consumption'
    configuration: { triggerType: 'Manual', replicaTimeout: 1800, replicaRetryLimit: 0, manualTriggerConfig: { parallelism: 1, replicaCompletionCount: 1 }, registries: registries, secrets: secrets }
    template: {
      containers: [{ name: 'migrate', image: image, resources: { cpu: json('0.5'), memory: '1Gi' }, env: concat(commonEnv, [{ name: 'ALICE_ROLE', value: 'migrate' }, { name: 'MIGRATE_APPLY', value: '1' }, { name: 'MIGRATE_SOURCE', value: '/mnt/alice/migrate/substrate.db' }]), volumeMounts: mounts }]
      volumes: volumes
    }
  }
  dependsOn: [identityAcrPull, identityKvRead, dbUrlSecret, pgDatabase]
}

// ---------------- the apps (stage apps): one replica each (in-process locks and background work assume one process) ----------------
resource web 'Microsoft.App/containerApps@2024-03-01' = if (withApps) {
  name: webName
  location: location
  identity: { type: 'UserAssigned', userAssignedIdentities: { '${identity.id}': {} } }
  properties: {
    environmentId: env.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Multiple'
      ingress: { external: true, targetPort: 8000, transport: 'auto', allowInsecure: false, traffic: [{ latestRevision: true, weight: 100 }]
        customDomains: empty(customDomain) ? [] : [{ name: customDomain, bindingType: 'SniEnabled', certificateId: customDomainCertificateId }] }
      registries: registries
      secrets: concat(secrets, [{ name: 'web-auth-secret', keyVaultUrl: '${kvUri}secrets/web-auth-secret', identity: identity.id }])
    }
    template: {
      containers: [{
        name: 'web'
        image: image
        resources: { cpu: json('0.5'), memory: '1Gi' }
        env: concat(commonEnv, [
          { name: 'ALICE_ROLE', value: 'web' }
          { name: 'ALICE_TRUST_EASYAUTH', value: '1' }
          { name: 'SUBSTRATE_ALLOWED_HOSTS', value: empty(customDomain) ? webFqdn : '${webFqdn},${customDomain}' }
        ])
        volumeMounts: mounts
        probes: [for p in tcpProbes: union(p, { tcpSocket: { port: 8000 } })]
      }]
      scale: { minReplicas: 1, maxReplicas: 1 }
      volumes: volumes
    }
  }
  dependsOn: [identityAcrPull, identityKvRead, dbUrlSecret, pgDatabase]
}

// Entra sign-in in front of the web app: only you get in. /healthz stays open for the platform's probe; /signed-out is the
// static page after 'Sign out of Alice' (no data), outside sign-in so it doesn't sign you straight back in.
// /hooks/tradingview: TradingView alerts (Stefan's decision, 4 Oct 2026); it only records a signal and checks its own token,
// size, rate and TradingView's sending addresses (trading.webhook).
resource webAuth 'Microsoft.App/containerApps/authConfigs@2024-03-01' = if (withApps) {
  parent: web
  name: 'current'
  properties: {
    platform: { enabled: true }
    globalValidation: { unauthenticatedClientAction: 'RedirectToLoginPage', redirectToProvider: 'azureactivedirectory', excludedPaths: ['/healthz', '/signed-out', '/hooks/tradingview'] }
    identityProviders: {
      azureActiveDirectory: {
        enabled: true
        registration: {
          clientId: webAuthClientId
          clientSecretSettingName: 'web-auth-secret'
          openIdIssuer: '${environment().authentication.loginEndpoint}${tenant().tenantId}/v2.0'
        }
        validation: {
          allowedAudiences: [webAuthClientId, 'api://${webAuthClientId}']
          defaultAuthorizationPolicy: { allowedPrincipals: { identities: union([ownerObjectId], allowedUserObjectIds) } }
        }
        // Ask who you are at every new Alice session (password, Windows Hello or passkey, plus MFA), even when the browser
        // is still signed in to Microsoft. Without it, after 'Sign out of Alice' anyone at the device could sign straight back in.
        // domain_hint=organizations: work or school accounts only, so an old personal Microsoft account with the same email
        // address is never offered (AADSTS50020 'from identity provider live.com').
        login: { loginParameters: askEverySignIn ? ['prompt=login', 'domain_hint=organizations'] : ['domain_hint=organizations'] }
      }
    }
    // A session lasts 8 hours from sign-in, then you sign in again (signins.SESSION_HOURS matches).
    login: { preserveUrlFragmentsForLogins: true, cookieExpiration: { convention: 'FixedTime', timeToExpiration: '08:00:00' } }
  }
}

resource mcp 'Microsoft.App/containerApps@2024-03-01' = if (withApps) {
  name: mcpName
  location: location
  identity: { type: 'UserAssigned', userAssignedIdentities: { '${identity.id}': {} } }
  properties: {
    environmentId: env.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Multiple'
      ingress: { external: true, targetPort: 8002, transport: 'auto', allowInsecure: false, traffic: [{ latestRevision: true, weight: 100 }] }
      registries: registries
      secrets: concat(secrets, connectorSecrets)
    }
    template: {
      containers: [{
        name: 'mcp'
        image: image
        resources: { cpu: json('0.5'), memory: '1Gi' }
        env: concat(commonEnv, [
          { name: 'ALICE_ROLE', value: 'mcp' }
          { name: 'ALICE_EXT_TENANT_ID', value: tenant().tenantId }
          { name: 'ALICE_EXT_APP_ID', value: extAppId }
          { name: 'ALICE_EXT_ALLOWED_USERS', value: extAllowedUsers }
          { name: 'ALICE_EXT_CALLERS', value: extCallers }
          { name: 'ALICE_EXT_AUDIENCES', value: extAudiences }
          { name: 'ALICE_EXT_BASE_URL', value: 'https://${mcpFqdn}' }
          { name: 'ALICE_EXT_ALLOWED_HOSTS', value: mcpFqdn }
          { name: 'ALICE_EXT_HOST', value: '0.0.0.0' }
          { name: 'ALICE_EXT_PORT', value: '8002' }
          { name: 'ALICE_NO_SCHEDULER', value: '1' }
        ], connectorEnv)
        volumeMounts: mounts
        probes: [for p in tcpProbes: union(p, { tcpSocket: { port: 8002 } })]
      }]
      scale: { minReplicas: 1, maxReplicas: 1 }
      volumes: volumes
    }
  }
  dependsOn: [identityAcrPull, identityKvRead, dbUrlSecret, pgDatabase]
}

// ---------------- backups (with stage apps, once -Step backup has switched them on) ----------------
// The job gets only what it needs: the database address, its identity, where to write, who to email. Not the API keys.
var backupJobEnv = concat([
  { name: 'ALICE_DATABASE_URL', secretRef: 'database-url' }
  { name: 'ALICE_OWNER_NAME', value: ownerName }
  { name: 'ALICE_AUDIT_STDOUT', value: '1' }
  { name: 'ALICE_IDENTITY_CLIENT_ID', value: identity.properties.clientId }
  { name: 'ALICE_MAIL_FROM', value: mailFrom }
  { name: 'ALICE_PUBLIC_URL', value: publicUrl }
], backupEnv)

module backups 'backup.bicep' = if (withBackup) {
  name: 'alice-backup'
  params: {
    location: location
    offsiteLocation: offsiteLocation
    prefix: prefix
    environmentName: env.name
    identityName: identity.name
    storageAccountName: storage.name
    shareName: share.name
    pgServerName: pg.name
    vaultName: backupVaultName
    offsiteName: offsiteName
    image: image
    registries: registries
    secrets: [{ name: 'database-url', keyVaultUrl: '${kvUri}secrets/database-url', identity: identity.id }]
    env: backupJobEnv
    filesRetentionDays: filesBackupDays
    offsiteKeepDays: offsiteKeepDays
    offsiteSoftDeleteDays: offsiteSoftDeleteDays
    immutabilityLocked: offsiteImmutabilityLocked
    lockResourceGroup: lockResourceGroup
    deployerObjectId: deployerObjectId
  }
  dependsOn: [identityAcrPull, identityKvRead, dbUrlSecret, envFiles]
}

output acrName string = acr.name
output acrLoginServer string = acr.properties.loginServer
output keyVaultName string = kv.name
output storageAccount string = storage.name
output shareName string = share.name
output environmentDomain string = env.properties.defaultDomain
output webUrl string = 'https://${webFqdn}'
output mcpUrl string = 'https://${mcpFqdn}'
output postgresServer string = pg.name
output offsiteAccount string = withBackup ? offsiteName : ''
output backupVault string = withBackup ? backupVaultName : ''
